/* GENERATED by design/build.mjs from design/tokens.json and design/icons.json. Do not edit. */
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/** Airship boot sprite, pre-scaled 4x to 144x60, 4-bit indexed. Draw at zoom 1. */
extern const lv_img_dsc_t dg_img_airship;
/** Hester hare, 8x8, 1-bit indexed in phosphor. */
extern const lv_img_dsc_t dg_img_hester8;

#ifdef __cplusplus
}
#endif
