/* GENERATED by design/build.mjs from design/tokens.json and design/icons.json. Do not edit. */
#pragma once

/* Colour tokens as 0xRRGGBB, for lv_color_hex(). */
#define DG_GROUND_0 0x07110d  /* Terminal, T-Deck screen, deepest wells */
#define DG_GROUND_1 0x0a1410  /* Chrome: title, tab, status and nav bars */
#define DG_GROUND_2 0x0d1a14  /* Content background */
#define DG_GROUND_3 0x13261e  /* Raised: rows, cards, inputs, hover */
#define DG_GROUND_4 0x1a3028  /* Hairline borders, dividers */
#define DG_GROUND_5 0x2a4a3e  /* Strong borders, disabled fills, selected segments */
#define DG_TEXT_1 0xe6f0eb  /* Primary text */
#define DG_TEXT_2 0x9fbcb0  /* Secondary text, labels */
#define DG_TEXT_3 0x6b8a7e  /* Muted text and hints */
#define DG_PHOSPHOR 0x44aa99  /* Brand, primary action, online, active */
#define DG_PHOSPHOR_HI 0x56bba9  /* Hover and pressed primary */
#define DG_PHOSPHOR_DEEP 0x2a7466  /* Shaded phosphor (illustration, muted fills) */
#define DG_ON_PHOSPHOR 0x07110d  /* Text and icons on phosphor fills */
#define DG_LIT 0x7fe0c0  /* Focus ring, cursor, selection, links */
#define DG_EMBER 0xf0a04b  /* Needs you: warnings, approvals, acting */
#define DG_ERROR 0xe5604c  /* Errors, offline, destructive */
#define DG_INFO 0x6fb7d9  /* Neutral notices */

#define DG_OVERLAY_OPA 184
#define DG_RADIUS 2

/* ANSI 0-15, in order: black red green yellow blue magenta cyan white, then bright. */
#define DG_ANSI_PALETTE { 0x1a3028, 0xe5604c, 0x44aa99, 0xf0a04b, 0x6fb7d9, 0xc49bd9, 0x5cc8c0, 0xc4d8cf, 0x6b8a7e, 0xf08a79, 0x7fe0c0, 0xf5c07f, 0x9fd4f0, 0xdcbde9, 0x8fe3dc, 0xe6f0eb }
