/*
 * theme.hpp — Phosphor design tokens as LVGL colours, plus a handful of style
 * helpers shared across the four screens.
 *
 * The numeric tokens (DG_GROUND_0 etc.) come from theme_tokens.h, generated by
 * design/build.mjs — do not hand-edit that file.  This one is hand-written and
 * is where the token -> lv_color_t plumbing and the shared row/focus/button
 * styling live, so every screen_*.cpp draws the same chrome instead of each
 * hand-rolling its own hex literals.
 *
 * Deliberately plain functions rather than a shared lv_style_t: nothing here
 * is hot enough to need it (rows are rebuilt a few dozen times a screen, not
 * per frame), and every other widget in this codebase is already styled with
 * direct lv_obj_set_style_* calls, so this stays consistent with that.
 */
#pragma once

#include "lvgl.h"
#include "theme_tokens.h"

namespace dirigible_app::dg {

inline lv_color_t c(uint32_t hex) { return lv_color_hex(hex); }

inline lv_color_t ground0() { return c(DG_GROUND_0); }   // terminal, deepest wells
inline lv_color_t ground1() { return c(DG_GROUND_1); }   // chrome: header/footer/tab bars
inline lv_color_t ground2() { return c(DG_GROUND_2); }   // content background
inline lv_color_t ground3() { return c(DG_GROUND_3); }   // raised: rows, cards, inputs, hover
inline lv_color_t ground4() { return c(DG_GROUND_4); }   // hairline borders, dividers
inline lv_color_t ground5() { return c(DG_GROUND_5); }   // strong borders, disabled fills

inline lv_color_t text1() { return c(DG_TEXT_1); }       // primary text
inline lv_color_t text2() { return c(DG_TEXT_2); }       // secondary text, labels
inline lv_color_t text3() { return c(DG_TEXT_3); }       // muted text, hints, footer

inline lv_color_t phosphor()      { return c(DG_PHOSPHOR); }       // brand / primary / online
inline lv_color_t phosphor_hi()   { return c(DG_PHOSPHOR_HI); }    // hover / pressed primary
inline lv_color_t phosphor_deep() { return c(DG_PHOSPHOR_DEEP); }  // shaded phosphor
inline lv_color_t on_phosphor()   { return c(DG_ON_PHOSPHOR); }    // text/icons on phosphor fills

inline lv_color_t lit()   { return c(DG_LIT); }     // focus ring, cursor, selection
inline lv_color_t ember() { return c(DG_EMBER); }   // needs-you: warnings, approvals, acting
inline lv_color_t error() { return c(DG_ERROR); }   // errors, offline, destructive
inline lv_color_t info()  { return c(DG_INFO); }    // neutral notices

// ---------------------------------------------------------------------------
// Shared style helpers
// ---------------------------------------------------------------------------

/// A row-shaped surface: 24 px tall (caller sets height if different), radius
/// DG_RADIUS, idle background `bg` (ground-1 for list rows, ground-3 for
/// cards/inputs/chips — pass whichever the caller needs).
inline void style_row(lv_obj_t* obj, lv_color_t bg = ground1())
{
    lv_obj_set_height(obj, 24);
    lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, 0);
    lv_obj_set_style_bg_color(obj, bg, 0);
    lv_obj_set_style_radius(obj, DG_RADIUS, 0);
}

/// Trackball/keyboard focus: raised (ground-3) fill and a 1 px lit border.
/// Apply to any focusable row, button or input so focus never falls back to
/// the stock theme's blue.  LV_STATE_FOCUS_KEY is included alongside
/// LV_STATE_FOCUSED so a row focused via lv_group_focus_obj() (no click,
/// keyboard/trackball only) still lights up.
inline void style_focus(lv_obj_t* obj, lv_color_t bg = ground3())
{
    lv_obj_set_style_bg_color(obj, bg, LV_STATE_FOCUSED);
    lv_obj_set_style_bg_color(obj, bg, LV_STATE_FOCUS_KEY);
    lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_STATE_FOCUSED);
    lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_width(obj, 1, LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(obj, 1, LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_color(obj, lit(), LV_STATE_FOCUSED);
    lv_obj_set_style_border_color(obj, lit(), LV_STATE_FOCUS_KEY);
    lv_obj_set_style_border_opa(obj, LV_OPA_COVER, LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(obj, LV_OPA_COVER, LV_STATE_FOCUS_KEY);
}

/// Primary action: phosphor fill, on-phosphor text, phosphor-hi when pressed.
/// Caller still sets its own label colour to on_phosphor().
inline void style_primary_btn(lv_obj_t* obj)
{
    lv_obj_set_style_bg_opa(obj, LV_OPA_COVER, 0);
    lv_obj_set_style_bg_color(obj, phosphor(), 0);
    lv_obj_set_style_bg_color(obj, phosphor_hi(), LV_STATE_PRESSED);
    lv_obj_set_style_radius(obj, DG_RADIUS, 0);
}

/// An input's focused border: lit, 1px, plus a lit blinking caret.  Base
/// border colour is left to the caller (usually ground-4 or ground-5).
inline void style_input_focus(lv_obj_t* obj)
{
    lv_obj_set_style_border_color(obj, lit(), LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(obj, 2, LV_PART_CURSOR);
    lv_obj_set_style_border_side(obj, LV_BORDER_SIDE_BOTTOM, LV_PART_CURSOR);
    lv_obj_set_style_border_color(obj, lit(), LV_PART_CURSOR);
    lv_obj_set_style_anim_time(obj, 500, LV_PART_CURSOR);
}

}  // namespace dirigible_app::dg
