// GENERATED by design/build.mjs from design/tokens.json and design/icons.json. Do not edit.

import 'package:flutter/painting.dart';

/// Phosphor colour tokens, shared with Lee and Dirigible.
abstract final class Phosphor {
  /// Terminal, T-Deck screen, deepest wells
  static const ground0 = Color(0xFF07110D);

  /// Chrome: title, tab, status and nav bars
  static const ground1 = Color(0xFF0A1410);

  /// Content background
  static const ground2 = Color(0xFF0D1A14);

  /// Raised: rows, cards, inputs, hover
  static const ground3 = Color(0xFF13261E);

  /// Hairline borders, dividers
  static const ground4 = Color(0xFF1A3028);

  /// Strong borders, disabled fills, selected segments
  static const ground5 = Color(0xFF2A4A3E);

  /// Primary text
  static const text1 = Color(0xFFE6F0EB);

  /// Secondary text, labels
  static const text2 = Color(0xFF9FBCB0);

  /// Muted text and hints
  static const text3 = Color(0xFF6B8A7E);

  /// Brand, primary action, online, active
  static const phosphor = Color(0xFF44AA99);

  /// Hover and pressed primary
  static const phosphorHi = Color(0xFF56BBA9);

  /// Shaded phosphor (illustration, muted fills)
  static const phosphorDeep = Color(0xFF2A7466);

  /// Text and icons on phosphor fills
  static const onPhosphor = Color(0xFF07110D);

  /// Focus ring, cursor, selection, links
  static const lit = Color(0xFF7FE0C0);

  /// Needs you: warnings, approvals, acting
  static const ember = Color(0xFFF0A04B);

  /// Errors, offline, destructive
  static const error = Color(0xFFE5604C);

  /// Neutral notices
  static const info = Color(0xFF6FB7D9);

  static const overlay = Color(0xB807110D);

  static const radiusControl = 4.0;
  static const radiusCard = 8.0;
  static const radiusModal = 12.0;
}

/// Terminal ANSI palette.
abstract final class PhosphorAnsi {
  static const black = Color(0xFF1A3028);
  static const red = Color(0xFFE5604C);
  static const green = Color(0xFF44AA99);
  static const yellow = Color(0xFFF0A04B);
  static const blue = Color(0xFF6FB7D9);
  static const magenta = Color(0xFFC49BD9);
  static const cyan = Color(0xFF5CC8C0);
  static const white = Color(0xFFC4D8CF);
  static const brightBlack = Color(0xFF6B8A7E);
  static const brightRed = Color(0xFFF08A79);
  static const brightGreen = Color(0xFF7FE0C0);
  static const brightYellow = Color(0xFFF5C07F);
  static const brightBlue = Color(0xFF9FD4F0);
  static const brightMagenta = Color(0xFFDCBDE9);
  static const brightCyan = Color(0xFF8FE3DC);
  static const brightWhite = Color(0xFFE6F0EB);
}
