#!/usr/bin/env node
// Phosphor design system build.
//
// Reads design/tokens.json and design/icons.json and writes the generated
// token, icon and image files for Lee (Electron), Aeronaut (Flutter) and
// Dirigible (LVGL). Rasterizes the brand marks in design/marks/ with
// rsvg-convert and iconutil when run with --icons.
//
//   node design/build.mjs            # tokens, icons, bitmaps
//   node design/build.mjs --icons    # also app icons (needs rsvg-convert, iconutil)

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'design/tokens.json'), 'utf8'));
const icons = JSON.parse(readFileSync(join(root, 'design/icons.json'), 'utf8'));

const HEADER = 'GENERATED by design/build.mjs from design/tokens.json and design/icons.json. Do not edit.';
const colors = Object.fromEntries(Object.entries(tokens.color).map(([k, v]) => [k, v.value]));
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const upper = (s) => s.replace(/-/g, '_').toUpperCase();
const hex6 = (h) => h.replace('#', '').toLowerCase();
const rgb = (h) => [0, 2, 4].map((i) => parseInt(hex6(h).slice(i, i + 2), 16));

function write(rel, text) {
  const p = join(root, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, text);
  console.log('wrote', rel);
}

// ── Lee: CSS custom properties ──────────────────────────────────────────
{
  const [or, og, ob] = rgb(tokens.overlay.color);
  const lines = [`/* ${HEADER} */`, ':root {'];
  for (const [k, v] of Object.entries(colors)) {
    lines.push(`  --${k}: ${v};`);
    lines.push(`  --${k}-rgb: ${rgb(v).join(', ')};`);
  }
  lines.push(`  --overlay: rgba(${or}, ${og}, ${ob}, ${tokens.overlay.opacity});`);
  for (const [k, v] of Object.entries(tokens.radius)) lines.push(`  --radius-${k}: ${v}px;`);
  tokens.space.forEach((v, i) => lines.push(`  --space-${i}: ${v}px;`));
  lines.push(`  --font-ui: ${tokens.font.ui};`);
  lines.push(`  --font-mono: ${tokens.font.mono};`);
  lines.push('}', '');
  write('electron/src/renderer/styles/tokens.css', lines.join('\n'));
}

// ── Lee: TS tokens (xterm themes, canvas code) and icon data ────────────
{
  const colorObj = Object.entries(colors).map(([k, v]) => `  '${k}': '${v}',`).join('\n');
  const ansi = tokens.ansi;
  write('electron/src/renderer/theme/tokens.generated.ts', `// ${HEADER}

export const colors = {
${colorObj}
} as const;

export type ColorToken = keyof typeof colors;

/** xterm.js ITheme built from the Phosphor tokens. */
export const xtermTheme = {
  background: colors['ground-0'],
  foreground: colors['text-1'],
  cursor: colors.lit,
  cursorAccent: colors['ground-0'],
  selectionBackground: 'rgba(127, 224, 192, 0.25)',
${Object.entries(ansi).map(([k, v]) => `  ${k}: '${v}',`).join('\n')}
};

export const fontMono = ${JSON.stringify(tokens.font.mono)};
export const fontUi = ${JSON.stringify(tokens.font.ui)};
`);

  const h = icons.glyphs.hester;
  const entries = Object.entries(icons.stroke).map(([k, d]) => `  '${k}': '${d}',`).join('\n');
  write('electron/src/renderer/icons/iconData.generated.ts', `// ${HEADER}

/** Stroke icons on a 24-unit grid. Render with stroke, no fill. */
export const strokeIcons = {
${entries}
} as const;

export type IconName = keyof typeof strokeIcons;

/** Hester hare silhouette. Filled; the eye is cut out at 24px and up. */
export const hesterGlyph = {
  viewBox: '${h.viewBox}',
  paths: ${JSON.stringify(h.paths)},
  eye: ${JSON.stringify(h.eye)},
} as const;
`);
}

// ── Aeronaut: Dart tokens and icon SVG strings ──────────────────────────
{
  const argb = (h) => `Color(0xFF${hex6(h).toUpperCase()})`;
  const c = Object.entries(colors).map(([k, v]) => `  /// ${tokens.color[k].role}\n  static const ${camel(k)} = ${argb(v)};`).join('\n\n');
  const a = Object.entries(tokens.ansi).map(([k, v]) => `  static const ${k} = ${argb(v)};`).join('\n');
  write('aeronaut/lib/theme/phosphor_tokens.dart', `// ${HEADER}

import 'package:flutter/painting.dart';

/// Phosphor colour tokens, shared with Lee and Dirigible.
abstract final class Phosphor {
${c}

  static const overlay = Color(0x${Math.round(tokens.overlay.opacity * 255).toString(16).toUpperCase().padStart(2, '0')}${hex6(tokens.overlay.color).toUpperCase()});

  static const radiusControl = ${tokens.radius.control}.0;
  static const radiusCard = ${tokens.radius.card}.0;
  static const radiusModal = ${tokens.radius.modal}.0;
}

/// Terminal ANSI palette.
abstract final class PhosphorAnsi {
${a}
}
`);

  const svg = (d) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"><path d="${d}"/></svg>`;
  const h = icons.glyphs.hester;
  const hesterSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${h.viewBox}">${h.paths.map((p) => `<path fill="#000" d="${p}"/>`).join('')}</svg>`;
  const names = Object.entries(icons.stroke).map(([k, d]) => `  static const ${camel(k)} = PhosphorIconData('${k}', '${svg(d)}');`).join('\n');
  write('aeronaut/lib/theme/phosphor_icons.generated.dart', `// ${HEADER}

/// SVG source for one Phosphor icon. Render with [PhosphorIcon].
class PhosphorIconData {
  const PhosphorIconData(this.name, this.svg, {this.filled = false});
  final String name;
  final String svg;
  final bool filled;
}

abstract final class PhosphorIcons {
${names}

  /// Hester hare silhouette (filled).
  static const hester = PhosphorIconData('hester', '${hesterSvg}', filled: true);
}
`);
}

// ── Dirigible: C header and LVGL images ─────────────────────────────────
{
  const defs = Object.entries(colors).map(([k, v]) => `#define DG_${upper(k)} 0x${hex6(v)}  /* ${tokens.color[k].role} */`).join('\n');
  const ansi = Object.values(tokens.ansi).map((v) => `0x${hex6(v)}`).join(', ');
  write('dirigible/firmware/main/theme_tokens.h', `/* ${HEADER} */
#pragma once

/* Colour tokens as 0xRRGGBB, for lv_color_hex(). */
${defs}

#define DG_OVERLAY_OPA ${Math.round(tokens.overlay.opacity * 255)}
#define DG_RADIUS ${tokens.radius.tdeck}

/* ANSI 0-15, in order: black red green yellow blue magenta cyan white, then bright. */
#define DG_ANSI_PALETTE { ${ansi} }
`);

  // Indexed images. lv_color32_t is stored B, G, R, A.
  const pal = (hexes) => hexes.map((h) => {
    if (!h) return '0x00, 0x00, 0x00, 0x00';
    const [r, g, b] = rgb(h);
    return `0x${b.toString(16).padStart(2, '0')}, 0x${g.toString(16).padStart(2, '0')}, 0x${r.toString(16).padStart(2, '0')}, 0xff`;
  });
  const bytes = (arr) => arr.map((b) => `0x${b.toString(16).padStart(2, '0')}`).join(', ');

  const ship = icons.pixel.airship;
  const keys = [...new Set(ship.rows.join('').replace(/\./g, ''))];
  const palHex = [null, ...keys.map((k) => colors[ship.palette[k]])];
  while (palHex.length < 16) palHex.push(null);
  // LVGL 8 cannot zoom indexed images, so the sprite is pre-scaled.
  const SCALE = 4;
  const rows = ship.rows.flatMap((r) => Array(SCALE).fill([...r].map((ch) => ch.repeat(SCALE)).join('')));
  const w = rows[0].length, hgt = rows.length;
  const shipPx = [];
  for (const row of rows) {
    for (let x = 0; x < w; x += 2) {
      const i0 = row[x] === '.' ? 0 : keys.indexOf(row[x]) + 1;
      const i1 = x + 1 < w ? (row[x + 1] === '.' ? 0 : keys.indexOf(row[x + 1]) + 1) : 0;
      shipPx.push((i0 << 4) | i1);
    }
  }

  const hare = icons.pixel['hester-8'];
  const harePx = hare.map((row) => [...row].reduce((b, ch, i) => b | ((ch === '#' ? 1 : 0) << (7 - i)), 0));

  write('dirigible/firmware/main/brand_images.h', `/* ${HEADER} */
#pragma once
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/** Airship boot sprite, pre-scaled 4x to ${w}x${hgt}, 4-bit indexed. Draw at zoom 1. */
extern const lv_img_dsc_t dg_img_airship;
/** Hester hare, 8x8, 1-bit indexed in phosphor. */
extern const lv_img_dsc_t dg_img_hester8;

#ifdef __cplusplus
}
#endif
`);
  write('dirigible/firmware/main/brand_images.c', `/* ${HEADER} */
#include "brand_images.h"

static const uint8_t airship_data[] = {
    /* palette: 16 x lv_color32_t (B, G, R, A) */
    ${pal(palHex).join(',\n    ')},
    /* pixels: 4 bpp, ${Math.ceil(w / 2)} bytes per row */
    ${bytes(shipPx)}
};

const lv_img_dsc_t dg_img_airship = {
    .header.cf = LV_IMG_CF_INDEXED_4BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = ${w},
    .header.h = ${hgt},
    .data_size = sizeof(airship_data),
    .data = airship_data,
};

static const uint8_t hester8_data[] = {
    ${pal([null, colors.phosphor]).join(',\n    ')},
    ${bytes(harePx)}
};

const lv_img_dsc_t dg_img_hester8 = {
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = 8,
    .header.h = 8,
    .data_size = sizeof(hester8_data),
    .data = hester8_data,
};
`);
}

// ── App icons ───────────────────────────────────────────────────────────
if (process.argv.includes('--icons')) {
  const rsvg = (src, w, out) => execFileSync('rsvg-convert', ['-w', String(w), '-h', String(w), join(root, src), '-o', join(root, out)]);

  // Lee (macOS): icon.png, icon_256.png, icon.icns, icon.svg
  rsvg('design/marks/lee.svg', 1024, 'electron/resources/icon.png');
  rsvg('design/marks/lee.svg', 256, 'electron/resources/icon_256.png');
  copyFileSync(join(root, 'design/marks/lee.svg'), join(root, 'electron/resources/icon.svg'));
  copyFileSync(join(root, 'design/marks/lee.svg'), join(root, 'electron/public/lee-mark.svg'));
  // About panel icon, served from public/ in dev and packaged builds.
  rsvg('design/marks/lee.svg', 512, 'electron/public/app-icon.png');
  const iconset = join(root, 'electron/resources/icon.iconset');
  rmSync(iconset, { recursive: true, force: true });
  mkdirSync(iconset);
  for (const s of [16, 32, 128, 256, 512]) {
    rsvg('design/marks/lee.svg', s, `electron/resources/icon.iconset/icon_${s}x${s}.png`);
    rsvg('design/marks/lee.svg', s * 2, `electron/resources/icon.iconset/icon_${s}x${s}@2x.png`);
  }
  execFileSync('iconutil', ['-c', 'icns', iconset, '-o', join(root, 'electron/resources/icon.icns')]);
  rmSync(iconset, { recursive: true, force: true });
  console.log('wrote electron/resources/icon.{png,icns,svg}, icon_256.png, public/lee-mark.svg, public/app-icon.png');

  // Aeronaut (iOS): full-bleed 1024 squares; flutter_launcher_icons slices them.
  mkdirSync(join(root, 'aeronaut/assets/brand'), { recursive: true });
  rsvg('design/marks/aeronaut-dark.svg', 1024, 'aeronaut/icon.png');
  rsvg('design/marks/aeronaut-light.svg', 1024, 'aeronaut/assets/brand/icon-light.png');
  rsvg('design/marks/aeronaut-dark.svg', 1024, 'aeronaut/assets/brand/icon-dark.png');
  rsvg('design/marks/aeronaut-tinted.svg', 1024, 'aeronaut/assets/brand/icon-tinted.png');
  copyFileSync(join(root, 'design/marks/hester.svg'), join(root, 'aeronaut/assets/brand/hester.svg'));
  console.log('wrote aeronaut/icon.png and assets/brand/*');
}
