import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:uuid/uuid.dart';

import '../models/machine.dart';
import '../models/pairing_payload.dart';
import '../providers/auth_provider.dart';
import '../providers/machines_provider.dart';
import '../services/copilot_api.dart';
import '../services/network_route.dart';
import '../theme/aeronaut_colors.dart';
import '../theme/aeronaut_theme.dart';

/// Camera-based QR scanner that pairs with a Lee instance.
///
/// Scans the QR code generated by Lee's Aeronaut Pairing dialog
/// (`aeronaut:get-pairing-qr` in `electron/src/main/main.ts`), parses it via
/// [PairingPayload] and either:
/// - **v2** (`ticket`, `pairVersion: 2`, contracts §4.2, §9.2): redeems the
///   single-use ticket at `POST /pair/redeem` to get a per-device token —
///   the shared token never leaves the machine in the QR;
/// - **v1** (`token`, older Lee): uses the token directly, as before.
///
/// Either way it creates or refreshes the [Machine] entry and navigates
/// back. Re-pairing the same `host:port` refreshes the token in place
/// rather than leaving a stale duplicate behind.
class QrScannerScreen extends ConsumerStatefulWidget {
  const QrScannerScreen({super.key});

  @override
  ConsumerState<QrScannerScreen> createState() => _QrScannerScreenState();
}

class _QrScannerScreenState extends ConsumerState<QrScannerScreen> {
  final MobileScannerController _controller = MobileScannerController(
    detectionSpeed: DetectionSpeed.normal,
    facing: CameraFacing.back,
  );
  bool _scanned = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _onDetect(BarcodeCapture capture) async {
    if (_scanned) return;

    final barcode = capture.barcodes.firstOrNull;
    if (barcode == null || barcode.rawValue == null) return;

    final payload = PairingPayload.parse(barcode.rawValue!);
    if (payload.kind == PairingPayloadKind.invalid) {
      _showError(payload.error ?? 'Invalid QR code.');
      return;
    }

    setState(() => _scanned = true);

    switch (payload.kind) {
      case PairingPayloadKind.ticket:
        await _redeemTicket(payload);
        break;
      case PairingPayloadKind.token:
        await _pairWithToken(payload);
        break;
      case PairingPayloadKind.invalid:
        break; // handled above
    }
  }

  /// The address to pair on: of the ones the QR carried, the first that
  /// answers, best first for where this phone is right now.
  Future<String> _pairingHost(PairingPayload payload) async {
    final candidates = Machine(
      id: '',
      name: '',
      host: payload.host!,
      lanHost: payload.lanHost,
      tailnetHost: payload.tailnetHost,
    ).hostCandidates(onTailnet: await deviceOnTailnet());
    if (candidates.length == 1) return candidates.first;
    return await firstReachableHost(candidates, payload.hostPort ?? 9001) ?? payload.host!;
  }

  Future<void> _pairWithToken(PairingPayload payload) async {
    final host = await _pairingHost(payload);
    final machine = Machine(
      id: const Uuid().v4(),
      name: (payload.name != null && payload.name!.isNotEmpty) ? payload.name! : host,
      host: host,
      lanHost: payload.lanHost,
      tailnetHost: payload.tailnetHost,
      hostPort: payload.hostPort ?? 9001,
      hesterPort: payload.hesterPort ?? 9000,
      token: payload.token!,
    );
    await _savePaired(machine);
  }

  Future<void> _redeemTicket(PairingPayload payload) async {
    final host = await _pairingHost(payload);
    final hostPort = payload.hostPort ?? 9001;
    final api = PairingApi(host: host, hostPort: hostPort);
    final PairRedeemResult result;
    try {
      result = await api.redeem(
        ticket: payload.ticket!,
        device: _deviceName(),
        kind: 'aeronaut',
      );
    } finally {
      api.dispose();
    }
    if (!mounted) return;

    if (!result.isApproved) {
      setState(() => _scanned = false);
      _showError(
        result.isExpired
            ? 'QR expired, show a new one on Lee.'
            : (result.error ?? 'Pairing failed.'),
      );
      return;
    }

    final machine = Machine(
      id: const Uuid().v4(),
      name: (payload.name != null && payload.name!.isNotEmpty)
          ? payload.name!
          : (result.name ?? host),
      host: host,
      lanHost: payload.lanHost,
      tailnetHost: payload.tailnetHost,
      hostPort: hostPort,
      hesterPort: result.hesterPort ?? payload.hesterPort ?? 9000,
      token: result.token!,
      deviceId: result.deviceId,
    );
    await _savePaired(machine);
  }

  Future<void> _savePaired(Machine machine) async {
    // Re-pairing the same host:port refreshes the token in place rather than
    // leaving a stale duplicate behind.
    await ref.read(machinesProvider.notifier).addOrUpdateMachine(machine);
    // A fresh token clears any standing "token rejected" banner.
    ref.read(authGuardProvider.notifier).reset();

    if (mounted) {
      Navigator.of(context).pop(true);
    }
  }

  /// A short label for the device record Lee keeps (contracts §4.1) — shown
  /// in Lee's Devices list, not user-editable here in v0.
  String _deviceName() {
    final label = switch (defaultTargetPlatform) {
      TargetPlatform.iOS => 'iPhone',
      TargetPlatform.android => 'Android',
      TargetPlatform.macOS => 'Mac',
      _ => 'Device',
    };
    return 'Aeronaut ($label)';
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: AeronautColors.offline,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Scan QR Code'),
      ),
      body: Column(
        children: [
          Expanded(
            child: ClipRRect(
              borderRadius: BorderRadius.circular(AeronautTheme.radiusMd),
              child: MobileScanner(
                controller: _controller,
                onDetect: _onDetect,
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(AeronautTheme.spacingLg),
            child: Text(
              'Point your camera at the QR code shown in\nLee > View > Aeronaut Pairing',
              textAlign: TextAlign.center,
              style: AeronautTheme.subheadline.copyWith(
                color: AeronautColors.textSecondary,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
