import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:uuid/uuid.dart';

import '../models/machine.dart';
import '../providers/machines_provider.dart';
import '../theme/aeronaut_colors.dart';
import '../theme/aeronaut_theme.dart';

/// Camera-based QR scanner that pairs with a Lee instance.
///
/// Scans the QR code generated by Lee's Aeronaut Pairing dialog,
/// parses the JSON payload, creates a Machine entry, and navigates back.
class QrScannerScreen extends ConsumerStatefulWidget {
  const QrScannerScreen({super.key});

  @override
  ConsumerState<QrScannerScreen> createState() => _QrScannerScreenState();
}

class _QrScannerScreenState extends ConsumerState<QrScannerScreen> {
  final MobileScannerController _controller = MobileScannerController(
    detectionSpeed: DetectionSpeed.normal,
    facing: CameraFacing.back,
  );
  bool _scanned = false;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _onDetect(BarcodeCapture capture) async {
    if (_scanned) return;

    final barcode = capture.barcodes.firstOrNull;
    if (barcode == null || barcode.rawValue == null) return;

    final raw = barcode.rawValue!;

    // Try to parse as Lee pairing JSON
    Map<String, dynamic>? payload;
    try {
      payload = jsonDecode(raw) as Map<String, dynamic>;
    } catch (_) {
      _showError('Invalid QR code - not a Lee pairing code.');
      return;
    }

    // Validate required fields
    final host = payload['host'] as String?;
    final name = payload['name'] as String?;
    if (host == null || host.isEmpty) {
      _showError('QR code missing host address.');
      return;
    }

    setState(() => _scanned = true);

    final machine = Machine(
      id: const Uuid().v4(),
      name: name ?? host,
      host: host,
      hostPort: (payload['hostPort'] as int?) ?? 9001,
      hesterPort: (payload['hesterPort'] as int?) ?? 9000,
      token: (payload['token'] as String?) ?? '',
    );

    await ref.read(machinesProvider.notifier).addMachine(machine);

    if (mounted) {
      Navigator.of(context).pop(true);
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: AeronautColors.offline,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Scan QR Code'),
      ),
      body: Column(
        children: [
          Expanded(
            child: ClipRRect(
              borderRadius: BorderRadius.circular(AeronautTheme.radiusMd),
              child: MobileScanner(
                controller: _controller,
                onDetect: _onDetect,
              ),
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(AeronautTheme.spacingLg),
            child: Text(
              'Point your camera at the QR code shown in\nLee > View > Aeronaut Pairing',
              textAlign: TextAlign.center,
              style: AeronautTheme.body.copyWith(
                color: AeronautColors.textSecondary,
                fontSize: 14,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
