// GENERATED by design/build.mjs from design/tokens.json and design/icons.json. Do not edit.

export const colors = {
  'ground-0': '#07110d',
  'ground-1': '#0a1410',
  'ground-2': '#0d1a14',
  'ground-3': '#13261e',
  'ground-4': '#1a3028',
  'ground-5': '#2a4a3e',
  'text-1': '#e6f0eb',
  'text-2': '#9fbcb0',
  'text-3': '#6b8a7e',
  'phosphor': '#44aa99',
  'phosphor-hi': '#56bba9',
  'phosphor-deep': '#2a7466',
  'on-phosphor': '#07110d',
  'lit': '#7fe0c0',
  'ember': '#f0a04b',
  'error': '#e5604c',
  'info': '#6fb7d9',
} as const;

export type ColorToken = keyof typeof colors;

/** xterm.js ITheme built from the Phosphor tokens. */
export const xtermTheme = {
  background: colors['ground-0'],
  foreground: colors['text-1'],
  cursor: colors.lit,
  cursorAccent: colors['ground-0'],
  selectionBackground: 'rgba(127, 224, 192, 0.25)',
  black: '#1a3028',
  red: '#e5604c',
  green: '#44aa99',
  yellow: '#f0a04b',
  blue: '#6fb7d9',
  magenta: '#c49bd9',
  cyan: '#5cc8c0',
  white: '#c4d8cf',
  brightBlack: '#6b8a7e',
  brightRed: '#f08a79',
  brightGreen: '#7fe0c0',
  brightYellow: '#f5c07f',
  brightBlue: '#9fd4f0',
  brightMagenta: '#dcbde9',
  brightCyan: '#8fe3dc',
  brightWhite: '#e6f0eb',
};

export const fontMono = "'JetBrains Mono', 'SF Mono', ui-monospace, Menlo, monospace";
export const fontUi = "-apple-system, BlinkMacSystemFont, 'SF Pro Text', system-ui, sans-serif";
